version: "3.8"

services:
  app:
    build: .
    container_name: civilens-app
    ports:
      - "8080:8080"
    environment:
      - APP_SERVER_URL=https://swagger-8fzm.onrender.com
    networks:
      - civilens-network

networks:
  civilens-network:
    driver: bridge
